apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dvpwa-dgtt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dvpwa-dgtt
    app.kubernetes.io/part-of: my-vulnerable-app-1
  name: dvpwa-dgtt
  namespace: rh-ee-ellin-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: dvpwa-dgtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: dvpwa-dgtt
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:9hdj3-dvpwa-dgtt
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
