apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: govwa-cnnz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: govwa-cnnz
    app.kubernetes.io/part-of: my-vulnerable-app-1
  name: govwa-cnnz
  namespace: rh-ee-ellin-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: govwa-cnnz
    weight: 100
status: {}
